#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool
sed -i "s/%TAG%/$DOCKER_TAG/g" img-z-jdk11.manifest.yaml
./manifest-tool push from-spec img-z-jdk11.manifest.yaml